output_dir: "/leonardo_scratch/large/userexternal/lmoroni0/instruct_tuning_voc_adapt/mistral_base_continued_news-summary"
model_name: "/leonardo_scratch/large/userexternal/lmoroni0/vocab_adaptation/full_mistral_continued_en1_it3/checkpoints/huggingface/ba2000"
use_lora: false
# Template
response_template: "###Summary:"
prompt_template: "###Text:"
# Training Parameters
training_bs: 1
evaluation_bs: 4
num_train_epochs: 3
## Optimizer Parameters
weight_decay: 0.005
learning_rate: 0.00001
lr_scheduler_type: "linear"
warmup_ratio: 0.3